### ISSUE TITLE
Grunt support.

### ISSUE THREAD

**Issue by coldlamper** [zertosh/loose-envify#5]
Does loose-envify support grunt?
When I use options like 

```
transform: [
               [
                'loose-envify',
                {
                    global: true,
                    NODE_ENV: 'production',
                    _: 'purge'
                }
            ]
        ],
```

they seem to be ignored. processs.env.NODE_ENV is always replaced with the current NODE_ENV variable and not the one in the options.

**Comment by zertosh** [comment]
Sorry, that's outside the scope of this project.
